### ISSUE TITLE
In-cart products deleted too fast

### ISSUE THREAD

**Issue by Arcantide** [jessepearson/cron-helper-for-woocommerce-bookings#1]
Hi!
Thanks for your nice plugin which helps me to erase all old in-cart products.
May I ask if it's possible the plugin changes also the regular delay which an in-cart product is deleted?
Normally, an in-cart product remains 60 minutes but I discovered the carts were deleted in around 5 minutes!
As your cron starts every 5 minutes, both situations could be linked?
Thanks in advance for your reply.
And sorry for my poor English -_-
Kind regards,
Florent

**Comment by jessepearson** [comment]
Hey Florent @Arcantide !

This plugin shouldn't change the delay timing for when in cart bookings expire. The code that runs to remove the bookings only looks for already expired in cart bookings, so there must be something else that's setting them to expire after 5 minutes (or less). The code that runs is here:

https://github.com/jessepearson/cron-helper-for-woocommerce-bookings/blob/main/cron-helper-for-woocommerce-bookings.php#L85-L98

This is the same thing as going to WooCommerce > Status > Tools, and clicking the button to remove expired in cart Bookings. 

It's possible you may have a filter set up to reduce the in cart booking time. Maybe something similar to this:
https://gist.github.com/jessepearson/da774da90618ec900d61fef7e34263b9

In either case, if you have an active subscription for Bookings, you can get support through WooCommerce.com, and they can help you investigate.

**Comment by Arcantide** [comment]
Hi Jesse,

Thanks for your useful reply.

I guess it is a cookie issue because, as you’ve mentioned it, your plugin doesn’t change the expiration delay.

I’m gonna search deeper this way.

Kind regards,
Florent

**Comment by Arcantide** [comment]
Hi Jesse,

I made several tests to find why my in-cart bookable products were cleared too soon.

I notice something probably interesting.

If I add a product and then, from the scheduled actions board click on « run now » for your cron-helper-for-woocommerce-bookings cron, the in-cart bookable product instantly be cleared!

So, I don’t know why it considers this fresh new in-cart bookable product has an expired one, but it is always the case.

If I wait 5 minutes instead of « forcing » the process, I have the same result.

I made a video to illustrate: https://www.loom.com/share/3abb443a0b17472985ba561aa10b89d3

Kind regards,
Florent

**Comment by jessepearson** [comment]
Hey Florent,

I can't really support how Bookings itself is acting, that would be the job of the support staff at WooCommerce.com. The code executed in this plugin calls default code in Bookings itself. If you can try your test again by adding the item to the cart, then going to WooCommerce > Status > Tools and using the _Clear expired In Cart bookings_ tool, and seeing what the results are. If the results are the same, It's likely the filter I mentioned before, as that tool checks the filter.

In either case, I would recommend reaching out to the staff at WooCommerce.com, as long as your subscription for Bookings is still active.

**Comment by Arcantide** [comment]
Hi Jesse,

Just to let you know that using Clear the expired In Cart bookings tools clear ALL the in-cart bookable products (even fresh one)

So you think this is the source of the issue?

As you’re plugin activate this every 5 minutes, no matter if a customer just added his product in the cart, all carts will be cleared…

What is your suggestion please?

Kind regards,
Florent

**Comment by jessepearson** [comment]
If you are using the tool under WooCommerce > Status > Tools, and it is clearing _all_ of the in cart bookings, then it is either the filter I mentioned or a bug with WooCommerce Bookings itself. The support team at WooCommerce.com should be contacted for further assistance.
